# Generated by Django 4.0.6 on 2022-07-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('c_logo', models.ImageField(upload_to='uploads')),
                ('hr_sign', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('x', 'Male'), ('y', 'Female')], default='', max_length=60, verbose_name='gender')),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('package', models.FloatField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.company')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=200)),
                ('no_of_days', models.IntegerField()),
                ('leave_type', models.CharField(blank=True, choices=[('0', 'Paid'), ('1', 'Unpaid')], default='', max_length=60, verbose_name='Leave type')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=100)),
                ('sm_type', models.CharField(blank=True, choices=[('0', 'Credited'), ('1', 'Debited')], default='', max_length=60, verbose_name='salary type')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.country')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('salary_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.salaryhead')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.position')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('leave_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.leavemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('leave_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.leavemaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmpResignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptence_date', models.DateField(blank=True, null=True)),
                ('resignation_recieved', models.DateField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.position'),
        ),
        migrations.CreateModel(
            name='EmpAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('efective_from', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.position')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.country')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.region')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.state')),
            ],
        ),
    ]
