# Generated by Django 4.0.6 on 2022-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_company_c_logo_alter_company_hr_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_logo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hr_sign',
            field=models.ImageField(upload_to='media'),
        ),
    ]
